// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later


#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * From https://config.qmk.fm/#/beekeeb/piantor/LAYOUT_split_3x6_3
 * and keymap.json
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TAB, KC_ESC, LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G, KC_H, LGUI_T(KC_J), LALT_T(KC_K), LCTL_T(KC_L), LSFT_T(KC_SCLN), KC_ESC, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, LT(1,KC_SPC), KC_LGUI, KC_ENT, LT(1,KC_SPC), KC_BSPC),
    [1] = LAYOUT_split_3x6_3(KC_LT, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_ESC, KC_GRV, KC_GRV, KC_QUOT, KC_MINS, KC_EQL, KC_EQL, KC_TAB, KC_LBRC, KC_RBRC, KC_PLUS, KC_BSLS, KC_NO, KC_NO, KC_ENT, KC_NO, KC_NO, KC_ENT, KC_DEL)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




